name: "Setup Node.js Environment"
description: "Checkout, setup Node.js and restore cache"
runs:
  using: "composite"
  steps:
    - name: 🤘 checkout
      uses: actions/checkout@v4

    - name: ⚙️ Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"

    - name: 🔄 Restore node_modules cache
      id: node_modules-cache
      uses: actions/cache/restore@v4
      with:
        key: node_modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
        path: node_modules

    - name: ⬇️ install
      shell: "bash"
      if: steps.node_modules-cache.outputs.cache-hit != 'true'
      run: |
        npm i -g npm@10
        npm ci --ignore-scripts --include=dev

    - name: 🔄 Save node_modules cache
      if: steps.node_modules-cache.outputs.cache-hit != 'true'
      continue-on-error: true
      uses: actions/cache/save@v4
      with:
        key: node_modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
        path: node_modules
