name: "Setup Node.js Environment"
description: "Checkout, setup Node.js and restore cache"
runs:
  using: "composite"
  steps:
    - name: 🤘 checkout
      uses: actions/checkout@v4

    - name: ⚙ Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"

    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: 🔄 Restore node_modules cache
      id: node_modules-cache
      uses: actions/cache/restore@v4
      with:
        key: node_modules-${{ runner.os }}-${{ hashFiles('package.json') }}-${{ hashFiles('bun.lockb') }}-v3
        path: ~/.bun/install/cache

    - name: ⬇ install
      shell: "bash"
      if: steps.node_modules-cache.outputs.cache-hit != 'true'
      run: bun install --frozen-lockfile

    - name: 🔄 Save node_modules cache
      if: steps.node_modules-cache.outputs.cache-hit != 'true'
      continue-on-error: true
      uses: actions/cache/save@v4
      with:
        key: node_modules-${{ runner.os }}-${{ hashFiles('package.json') }}-${{ hashFiles('bun.lockb') }}-v3
        path: ~/.bun/install/cache
